apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-app
  labels:
    app: gke-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-app
  template:
    metadata:
      labels:
        app: gke-app
    spec:
      containers:
      - name: gke-app
        image: IMAGE_PLACEHOLDER   # ðŸ‘ˆ Jenkins replaces this
        ports:
        - containerPort: 8080
